-- MySQL Script generated by MySQL Workbench
-- Sun Dec 25 22:59:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema faculdade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema faculdade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `faculdade` DEFAULT CHARACTER SET utf8 ;
USE `faculdade` ;

-- -----------------------------------------------------
-- Table `faculdade`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`professor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pontuario` VARCHAR(100) NULL,
  `professorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`curso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(5) NOT NULL,
  `duraçao` TINYINT NULL,
  `tipo_duraçao` ENUM('semestre', 'anual') NULL,
  `data_inicio` DATE NULL,
  `periodo` ENUM('vespertino', 'noturno', 'matutino') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`disciplina`
-- -----------------------------------------------------	
	CREATE TABLE IF NOT EXISTS `faculdade`.`disciplina` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(100) NULL,
	`sigla` VARCHAR(5) NULL,
	`semestre` TINYINT NULL,
	`aulas_semana` VARCHAR(45) NULL,
	`aulas_total` INT NULL,
	`disciplinacol` INT NULL,
	`area` VARCHAR(45) NULL,
	`curso_id` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`id`),
	INDEX `fk_disciplina_curso1_idx` (`curso_id` ASC) VISIBLE,
	CONSTRAINT `fk_disciplina_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `faculdade`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
	ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`truma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`truma` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(2) NOT NULL,
  `disciplina_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_truma_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  CONSTRAINT `fk_truma_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `faculdade`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`aluno` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NULL,
  `alunocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`sala` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `computadores` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `projetor` TINYINT NULL,
  `lousa_digital` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`aluno_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`aluno_curso` (
  `aluno_id` INT UNSIGNED NOT NULL,
  `curso_id` INT UNSIGNED NOT NULL,
  `situaçao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aluno_id`, `curso_id`),
  INDEX `fk_aluno_has_curso_curso1_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_curso_aluno_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_curso_aluno`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `faculdade`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_curso_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `faculdade`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`aluno_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`aluno_disciplina` (
  `aluno_id` INT UNSIGNED NOT NULL,
  `disciplina_id` INT UNSIGNED NOT NULL,
  `situaçao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aluno_id`, `disciplina_id`),
  INDEX `fk_aluno_has_disciplina_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_disciplina_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_disciplina_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `faculdade`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `faculdade`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`aluno_truma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`aluno_truma` (
  `aluno_id` INT UNSIGNED NOT NULL,
  `truma_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`aluno_id`, `truma_id`),
  INDEX `fk_aluno_has_truma_truma1_idx` (`truma_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_truma_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_truma_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `faculdade`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_truma_truma1`
    FOREIGN KEY (`truma_id`)
    REFERENCES `faculdade`.`truma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`professor_truma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`professor_truma` (
  `professor_id` INT UNSIGNED NOT NULL,
  `truma_id` INT UNSIGNED NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`professor_id`, `truma_id`),
  INDEX `fk_professor_has_truma_truma1_idx` (`truma_id` ASC) VISIBLE,
  INDEX `fk_professor_has_truma_professor1_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_professor_has_truma_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `faculdade`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_truma_truma1`
    FOREIGN KEY (`truma_id`)
    REFERENCES `faculdade`.`truma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `faculdade`.`truma_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `faculdade`.`truma_sala` (
  `truma_id` INT UNSIGNED NOT NULL,
  `sala_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`truma_id`, `sala_id`),
  INDEX `fk_truma_has_sala_sala1_idx` (`sala_id` ASC) VISIBLE,
  INDEX `fk_truma_has_sala_truma1_idx` (`truma_id` ASC) VISIBLE,
  CONSTRAINT `fk_truma_has_sala_truma1`
    FOREIGN KEY (`truma_id`)
    REFERENCES `faculdade`.`truma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_truma_has_sala_sala1`
    FOREIGN KEY (`sala_id`)
    REFERENCES `faculdade`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
